2024-07-21 07:56:52,470:DEBUG:certbot._internal.main:certbot version: 2.1.0
2024-07-21 07:56:52,470:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2024-07-21 07:56:52,470:DEBUG:certbot._internal.main:Arguments: ['--standalone', '--webroot', '-w', '/var/www/html', '-d', 'rmct.cn', '--email', '3475272270@qq.com', '--agree-tos', '--no-eff-email', '--non-interactive', '--test-cert']
2024-07-21 07:56:52,471:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-07-21 07:56:52,483:DEBUG:certbot._internal.log:Root logging level set at 30
2024-07-21 07:56:52,485:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1571, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/selection.py", line 208, in choose_configurator_plugins
    req_auth, req_inst = cli_plugin_requests(config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/selection.py", line 312, in cli_plugin_requests
    req_auth = set_configurator(req_auth, "webroot")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/selection.py", line 287, in set_configurator
    raise errors.PluginSelectionError(msg.format(repr(previously), repr(now)))
certbot.errors.PluginSelectionError: Too many flags setting configurators/installers/authenticators 'standalone' -> 'webroot'
2024-07-21 07:56:52,489:ERROR:certbot._internal.log:Too many flags setting configurators/installers/authenticators 'standalone' -> 'webroot'
